import { test, expect } from '@playwright/test'

test('first paint shows the brand before JS, then enters once with optional audio', async ({ page }, testInfo) => {
  let release!: () => void
  const hold = new Promise<void>((resolve) => { release = resolve })
  await page.route('**/assets/*.js', async (route) => { await hold; await route.continue() })
  await page.goto('/', { waitUntil: 'commit' })
  await expect(page.locator('#boot-enter')).toBeVisible()
  await expect(page.locator('#seo-root')).toBeHidden()
  await expect(page.locator('#app-root')).toBeEmpty()
  await expect(page.locator('#boot-audio')).not.toBeChecked()
  await page.screenshot({ path: testInfo.outputPath('boot-desktop.png') })
  await page.locator('#boot-audio').check()
  await page.locator('#boot-enter').click()
  await expect(page.locator('#boot-enter')).toHaveText('Abriendo experiencias…')
  release()
  await expect(page.locator('html')).toHaveClass(/app-ready/)
  await expect(page.locator('.top-tools button').last()).toHaveText('AUDIO ON')
  await expect(page.locator('#boot-root')).toBeHidden()
  await page.reload()
  await expect(page.locator('html')).toHaveClass(/boot-resuming/)
  await expect(page.locator('html')).toHaveClass(/app-ready/)
  await expect(page.locator('#boot-root')).toBeHidden()
})

test('the semantic page works without JavaScript', async ({ browser }) => {
  const context = await browser.newContext({ javaScriptEnabled: false })
  const page = await context.newPage()
  await page.goto('http://127.0.0.1:4187/proyectos/cielo-final')
  await expect(page.locator('#boot-root')).toBeHidden()
  await expect(page.locator('#seo-root')).toBeVisible()
  await expect(page.locator('h1')).toContainText('Cielofinal')
  await expect(page.locator('section[aria-labelledby="project-tracks"] article')).toHaveCount(6)
  await context.close()
})

test('a failed JavaScript download reveals the usable fallback', async ({ page }) => {
  await page.clock.install()
  await page.route('**/assets/*.js', (route) => route.abort())
  await page.goto('/', { waitUntil: 'domcontentloaded' })
  await page.clock.fastForward(11000)
  await expect(page.locator('#seo-root')).toBeVisible()
  await expect(page.locator('#boot-root')).toBeHidden()
  await expect(page.locator('#seo-root header a').first()).toBeVisible()
})

for (const width of [1600, 390]) {
  test(`vinyl cases, technologies and scroll at ${width}px`, async ({ page }, testInfo) => {
    test.setTimeout(90000)
    await page.setViewportSize({ width, height: width === 390 ? 844 : 900 })
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    for (const [slug, id, title] of [['metalmente-arte', 'metalmente', 'MetalMente Arte'], ['cielo-final', 'cielofinal', 'Cielofinal'], ['avvivo', 'avvivo', 'AVVIVO']]) {
      await page.goto(`/proyectos/${slug}`)
      await expect(page.locator('html')).toHaveClass(/app-ready/)
      await expect(page.locator('#boot-root')).toBeHidden()
      await expect(page.locator('.work-selector a')).toHaveCount(7)
      await expect(page.locator('#project-title')).toContainText(title)
      await expect(page.locator('.album-track__trigger[aria-expanded=true]')).toHaveCount(0)
      await expect(page.locator('.sleeve-vector')).toHaveJSProperty('complete', true)
      await page.locator('.sleeve-artwork img').scrollIntoViewIfNeeded()
      await expect.poll(() => page.locator('.sleeve-artwork img').evaluate((img: HTMLImageElement) => img.naturalWidth)).toBeGreaterThan(0)
      await expect(page.locator('.album-release')).toContainText('TELLOUNDER DEVELOPER')
      const sleeveSize = await page.locator('.album-sleeve').boundingBox()
      expect(Math.abs(sleeveSize!.width - sleeveSize!.height)).toBeLessThan(2)
      await page.locator('.album-sleeve').screenshot({ path: testInfo.outputPath(`${id}-jacket-${width}.png`), style: '.topbar,.statusbar{visibility:hidden}' })
      await page.locator('.album-track__trigger').first().click()
      const dialog = page.getByRole('dialog')
      await expect(dialog).toBeVisible()
      await expect(page.getByRole('button', { name: 'Cerrar notas' })).toBeFocused()
      const openedSize = await page.locator('.album-sleeve').boundingBox()
      expect(Math.abs(openedSize!.height - sleeveSize!.height)).toBeLessThan(1)
      expect(Math.abs(openedSize!.width - sleeveSize!.width)).toBeLessThan(1)
      await expect(page.locator('.track-story')).toHaveCount(1)
      await expect(page.locator('.record-label__logo').first()).toHaveJSProperty('complete', true)
      const centers = await page.locator('.project-record').evaluate((record) => {
        const a = record.getBoundingClientRect()
        const b = record.querySelector('.record-label')!.getBoundingClientRect()
        return Math.abs(a.x + a.width / 2 - b.x - b.width / 2) + Math.abs(a.y + a.height / 2 - b.y - b.height / 2)
      })
      expect(centers).toBeLessThan(1)
      await dialog.getByRole('button', { name: 'Siguiente' }).click()
      await expect(page.locator('.track-story')).toHaveCount(1)
      await expect(page.locator('.record-label small')).toContainText('TRK 02')
      const tech = dialog.locator('.technology-rail__items button').first()
      await tech.click()
      await expect(tech).toHaveAttribute('aria-expanded', 'true')
      await expect(dialog.locator('.technology-rail__detail')).toBeVisible()
      await tech.click()
      await expect(dialog.locator('.technology-rail__detail')).toBeHidden()
      await dialog.locator('.track-evidence summary').click()
      await expect(dialog.locator('.track-evidence p')).toBeVisible()
      await page.screenshot({ path: testInfo.outputPath(`${id}-${width}.png`) })
      expect(await dialog.evaluate((el) => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
      const lockedScroll = await page.evaluate(() => scrollY)
      await page.mouse.move(width / 2, 450)
      await page.mouse.wheel(0, 400)
      expect(await page.evaluate(() => scrollY)).toBe(lockedScroll)
      await page.keyboard.press('Escape')
      await expect(dialog).toHaveCount(0)
      await expect(page).toHaveURL(new RegExp(slug))
      await expect(page.locator('.album-track__trigger').first()).toBeFocused()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
      const before = await page.evaluate(() => scrollY)
      const panel = await page.locator('.album-sleeve').boundingBox()
      await page.mouse.move(Math.min(width - 15, (panel?.x ?? 0) + (panel?.width ?? 100) / 2), 500)
      await page.mouse.wheel(0, 450)
      await expect.poll(() => page.evaluate(() => scrollY)).toBeGreaterThan(before)
      await page.locator('.project-stack-trigger').click()
      await expect(page.getByRole('dialog').getByRole('heading', { name: 'Stack completo' })).toBeVisible()
      await expect(page.getByRole('dialog').locator('.technology-rail__items button').first()).toBeVisible()
      await page.getByRole('button', { name: 'Cerrar notas' }).click()
      await expect(page.getByRole('dialog')).toHaveCount(0)
    }
    expect(errors).toEqual([])
  })
}

test('all seven sleeves use background vector logos without halos or added layout height', async ({ page }, testInfo) => {
  test.setTimeout(90000)
  await page.setViewportSize({ width: 390, height: 844 })
  const sources = new Set<string>()
  for (const slug of ['avvivo', 'catalogo-aye', 'rise-difusion', 'hembra', 'anto-grispo', 'metalmente-arte', 'cielo-final']) {
    await page.goto(`/proyectos/${slug}`)
    await expect(page.locator('html')).toHaveClass(/app-ready/)
    const art = page.locator('.sleeve-artwork img')
    await art.scrollIntoViewIfNeeded()
    await expect.poll(() => art.evaluate((img: HTMLImageElement) => img.naturalWidth)).toBeGreaterThan(0)
    sources.add((await art.getAttribute('src'))!)
    const src = (await art.getAttribute('src'))!
    expect(src.includes('.svg') || src.startsWith('data:image/svg+xml')).toBe(true)
    const print = page.locator('.sleeve-artwork')
    await expect(print).toHaveCSS('position', 'absolute')
    await expect(print).toHaveCSS('mask-image', 'none')
    await expect(print).toHaveCSS('background-image', 'none')
    const title = await page.locator('.sleeve-title').boundingBox()
    const header = await page.locator('.album-release').boundingBox()
    expect(title!.y - header!.y - header!.height).toBeLessThan(35)
    const imageSource = await art.evaluate(async (img: HTMLImageElement) => (await fetch(img.src)).text())
    expect(imageSource).toContain('<path')
    expect(imageSource).not.toMatch(/<image\b|<rect\b|<linearGradient\b|<radialGradient\b/)
    await expect(page.locator('.album-release')).toContainText('TELLOUNDER DEVELOPER')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    const ring = await page.locator('.sleeve-ring-wear').boundingBox()
    expect(Math.abs(ring!.width - ring!.height)).toBeLessThan(2)
    const sleeve = await page.locator('.album-sleeve').boundingBox()
    expect(Math.abs(sleeve!.width - sleeve!.height)).toBeLessThan(2)
    expect(await page.locator('.album-sleeve').evaluate((el) => el.scrollHeight <= el.clientHeight + 2)).toBe(true)
    const lastTrack = await page.locator('.album-track__trigger').last().boundingBox()
    const stack = await page.locator('.project-stack-trigger').boundingBox()
    expect(lastTrack!.y + lastTrack!.height).toBeLessThanOrEqual(stack!.y + 1)
    if (['hembra', 'catalogo-aye', 'cielo-final'].includes(slug)) {
      await page.locator('.album-sleeve').screenshot({ path: testInfo.outputPath(`${slug}-printed-mobile.png`), style: '.topbar,.statusbar{visibility:hidden}' })
    }
  }
  expect(sources.size).toBe(7)
})

test('fixed jacket fits narrow phones and intermediate layouts, including long titles', async ({ page }) => {
  test.setTimeout(90000)
  for (const width of [320, 768, 1024]) {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/proyectos/avvivo')
    await expect(page.locator('html')).toHaveClass(/app-ready/)
    const sleeve = page.locator('.album-sleeve')
    const before = await sleeve.boundingBox()
    expect(Math.abs(before!.width - before!.height)).toBeLessThan(2)
    await page.locator('.album-track__title>span').first().evaluate((el) => { el.textContent = 'Un título deliberadamente extenso para comprobar que la tapa nunca cambie de tamaño al desbordar varias líneas de contenido' })
    const after = await sleeve.boundingBox()
    expect(Math.abs(after!.height - before!.height)).toBeLessThan(1)
    expect(await sleeve.evaluate((el) => el.scrollHeight <= el.clientHeight + 2)).toBe(true)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    // Measure the layout, not the intersecting axis-aligned bounds of a rotated jacket.
    await sleeve.evaluate((el: HTMLElement) => { el.style.transform = 'none' })
    const rows = await page.locator('.album-track__trigger').evaluateAll((elements) => elements.map((el) => el.getBoundingClientRect().toJSON()))
    for (let i = 1; i < rows.length; i++) expect(rows[i].top).toBeGreaterThanOrEqual(rows[i - 1].bottom - 1)
  }
})

test('notes trap focus, dismiss from backdrop and restore the untouched sleeve', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/proyectos/avvivo')
  const trigger = page.locator('.album-track__trigger').first()
  await trigger.click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toHaveCSS('animation-name', 'sleeve-notes-in')
  await expect(page.getByRole('button', { name: 'Cerrar notas' })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(dialog.getByRole('button', { name: 'Siguiente' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Cerrar notas' })).toBeFocused()
  await page.keyboard.press('7')
  await expect(page).toHaveURL(/avvivo/)
  await page.mouse.click(5, 5)
  await expect(dialog).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await expect(page.locator('html')).not.toHaveCSS('overflow', 'hidden')
})

test('new project shortcuts and pitch input remain independent', async ({ page }) => {
  await page.goto('/proyectos/avvivo')
  await expect(page.locator('html')).toHaveClass(/app-ready/)
  await page.keyboard.press('6')
  await expect(page).toHaveURL(/metalmente-arte/)
  await page.keyboard.press('7')
  await expect(page).toHaveURL(/cielo-final/)
  const pitch = page.getByRole('slider', { name: 'Velocidad del tocadiscos' })
  await pitch.focus()
  await pitch.press('ArrowRight')
  await expect(pitch).toHaveValue('1.05')
  await expect(page).toHaveURL(/cielo-final/)
})

test('mobile entry stays readable and the seven hero channels remain reachable', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.locator('#boot-enter')).toBeVisible()
  await expect(page.locator('#boot-audio')).not.toBeChecked()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('boot-mobile.png') })
  await page.locator('#boot-enter').click()
  await expect(page.locator('.top-tools button').last()).toHaveText('AUDIO OFF')
  const channel = page.locator('.amp-channel').last()
  await channel.scrollIntoViewIfNeeded()
  await expect(channel).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('hero-mobile.png') })
  await channel.click()
  await expect(page).toHaveURL(/cielo-final/)
})

test('vinyl keeps rotating and its pause control still works', async ({ page }) => {
  test.setTimeout(60000)
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/proyectos/metalmente-arte')
  const label = page.locator('.record-label')
  await expect(label).toBeVisible()
  const transform = await label.evaluate((element) => getComputedStyle(element).transform)
  await expect.poll(() => label.evaluate((element) => getComputedStyle(element).transform)).not.toBe(transform)
  await page.getByRole('button', { name: 'Pausar tocadiscos' }).click()
  await expect.poll(() => label.evaluate((element) => getComputedStyle(element).animationPlayState)).toBe('paused')
  await page.getByRole('button', { name: 'Reproducir tocadiscos' }).click()
  await expect.poll(() => label.evaluate((element) => getComputedStyle(element).animationPlayState)).toBe('running')
})
