export type ProjectId = 'avvivo' | 'aye' | 'rise' | 'hembra' | 'anto' | 'metalmente' | 'cielofinal'

export type ProjectTech = {
  name: string
  use: string
}

export type ProjectTrack = {
  title: string
  chapter: string
  summary: string
  signal: string
  decision: string
  result: string
  proof: string
  evidenceUrl?: string
  tech: ProjectTech[]
}

export type Project = {
  id: ProjectId
  number: string
  title: string
  subtitle: string
  type: string
  statement: string
  role: string
  accent: string
  url: string
  host: string
  embeddable: boolean
  repository?: string
  stack: ProjectTech[]
  tracks: ProjectTrack[]
}

export const projects: Project[] = [
  {
    id: 'avvivo',
    number: '01',
    title: 'AVVIVO',
    subtitle: 'Sistema principal',
    type: 'PRODUCT SYSTEM / HEADLINER',
    statement: 'Sistema que muestra actividad, conecta actores, aplica reglas y registra eventos.',
    role: 'Producto · UX · Frontend · Backend · Datos · Cloud · Operación',
    accent: '#ef0a3a',
    url: 'https://avellanedaenvivo.com.ar/',
    host: 'avellanedaenvivo.com.ar',
    embeddable: false,
    stack: [
      { name: 'React 19', use: 'Construye las superficies públicas, de Cliente, de Tienda y de Administración.' },
      { name: 'TypeScript 5.8', use: 'Tipa contratos, estados y respuestas entre la interfaz y los servicios.' },
      { name: 'Vite 5', use: 'Compila el frontend, separa chunks y publica una versión identificable.' },
      { name: 'React Router 6', use: 'Organiza rutas públicas, privadas y específicas para cada actor.' },
      { name: 'Google One Tap', use: 'Ofrece acceso asistido opcional mediante Google Identity Services, con botones manuales como respaldo.' },
      { name: 'Firebase Auth', use: 'Valida identidad y tokens utilizados por frontend y API.' },
      { name: 'API REST', use: 'Expone operaciones autenticadas y mantiene las reglas fuera de la interfaz.' },
      { name: 'Node.js 22', use: 'Ejecuta la API y los procesos operativos del backend.' },
      { name: 'Express 4', use: 'Organiza middleware, rutas y controladores HTTP del servicio principal.' },
      { name: 'Prisma 5', use: 'Modela el dominio y ejecuta consultas y transacciones tipadas.' },
      { name: 'PostgreSQL', use: 'Persiste identidades, tiendas, contenido, relaciones, comercio y auditoría.' },
      { name: 'Cloud SQL', use: 'Opera PostgreSQL en la infraestructura productiva de Google Cloud.' },
      { name: 'Redis', use: 'Sostiene caché, coordinación y canales Pub/Sub cuando el runtime lo requiere.' },
      { name: 'Cloud Run', use: 'Ejecuta la API y servicios de trabajo con despliegues independientes.' },
      { name: 'Background Workers', use: 'Procesan renders, mantenimiento y sincronizaciones fuera del request principal mediante servicios Node separados.' },
      { name: 'Google Cloud Storage', use: 'Guarda media pública y privada fuera de la base relacional.' },
      { name: 'FFmpeg + Sharp', use: 'Procesan video, metadatos, miniaturas e imágenes dentro de los workers.' },
      { name: 'MapLibre + Leaflet', use: 'Renderizan el mapa vectorial y mantienen un motor alternativo de respaldo.' },
      { name: 'Konva', use: 'Compone capas de media, texto, dibujo y stickers en el estudio de publicación.' },
      { name: 'Firebase Hosting', use: 'Sirve el frontend y dirige rutas de API hacia los servicios productivos.' },
      { name: 'Resend', use: 'Entrega correos transaccionales generados por eventos reales del sistema.' },
      { name: 'Web Push', use: 'Envía notificaciones a suscripciones autorizadas por el navegador.' },
      { name: 'Mercado Pago SDK', use: 'Integra la superficie de pagos habilitada para operaciones comerciales específicas.' },
    ],
    tracks: [
      {
        title: 'De actividad dispersa a sistema',
        chapter: 'NECESIDAD / SISTEMA',
        summary: 'La moda mayorista necesitaba algo más que una vidriera de tiendas.',
        signal: 'La actividad, el contenido, las relaciones y la operación vivían como piezas separadas, sin una lectura común.',
        decision: 'Modelé actores, estados, reglas y eventos antes de convertirlos en pantallas. Cliente, Tienda y Administración conservan responsabilidades distintas.',
        result: 'AVVIVO muestra actividad, conecta actores, aplica reglas y registra eventos dentro de un mismo producto operativo.',
        proof: 'La aplicación productiva expone recorridos diferenciados y una navegación gobernada por estado, sesión y tipo de actor.',
        tech: [
          { name: 'React 19', use: 'Compone las experiencias públicas, de Cliente, de Tienda y de Administración dentro del mismo producto.' },
          { name: 'TypeScript', use: 'Hace explícitos actores, datos y contratos compartidos entre la interfaz y los servicios.' },
          { name: 'API REST', use: 'Concentra las operaciones autenticadas y evita que las reglas del sistema vivan solamente en las pantallas.' },
          { name: 'Node.js + Express', use: 'Ejecuta el servicio principal y organiza middleware, rutas y controladores del dominio.' },
          { name: 'Prisma', use: 'Convierte el modelo de actores, actividad y operación en consultas y transacciones tipadas.' },
          { name: 'PostgreSQL', use: 'Persiste el dominio operativo y la evidencia que conecta las distintas superficies.' },
          { name: 'Cloud Run', use: 'Ejecuta la API y los servicios de trabajo como unidades productivas independientes.' },
        ],
      },
      {
        title: 'Cliente y Tienda, recorridos distintos',
        chapter: 'ACTORES / EXPERIENCIA',
        summary: 'Dos caras públicas conectadas, sin mezclarlas ni fingir que hacen lo mismo.',
        signal: 'Una persona explora y se relaciona; una Tienda publica, gestiona presencia y opera. Un único recorrido no podía responder a ambas.',
        decision: 'Diseñé superficies, permisos y navegación propios para Cliente y Tienda, con Administración como actor interno.',
        result: 'Cada actor entiende qué puede hacer, qué información ve y cómo una acción repercute en el resto del sistema.',
        proof: 'El producto contiene vistas y rutas específicas de Cliente y de Tienda, además de herramientas internas de Administración.',
        tech: [
          { name: 'Google One Tap', use: 'Ofrece acceso asistido con Google Identity Services sin reemplazar los botones manuales de ingreso.' },
          { name: 'Firebase Auth', use: 'Mantiene la identidad de sesión que habilita el recorrido correcto.' },
          { name: 'React Router', use: 'Organiza rutas públicas, privadas y específicas por experiencia.' },
          { name: 'API REST', use: 'Resuelve el actor y devuelve capacidades sin delegar permisos al navegador.' },
          { name: 'PostgreSQL', use: 'Conserva perfiles y relaciones de dominio que continúan más allá del token de acceso.' },
          { name: 'Reglas de dominio', use: 'Evitan convertir permisos y estados en simples decisiones visuales del frontend.' },
        ],
      },
      {
        title: 'Reels y Vivos con estado real',
        chapter: 'ACTIVIDAD / MEDIA',
        summary: 'El contenido no es una miniatura: tiene reproducción, tiempo y contexto.',
        signal: 'La actividad de una Tienda debía sentirse actual sin confundir una publicación persistente con una emisión en curso.',
        decision: 'Separé Reels y Vivos, y construí reproducción, pausa, audio, progreso y salida de viewport como estados observables.',
        result: 'Cliente puede recorrer actividad audiovisual y abrir su contexto; Tienda dispone de superficies para gestionarla.',
        proof: 'Las vistas implementan controles de reproducción, progreso, silencio y pausa al salir de pantalla, además del acceso al contexto de actividad.',
        tech: [
          { name: 'React', use: 'Sincroniza estado de reproducción, visibilidad, controles y apertura del contexto.' },
          { name: 'Web Media', use: 'Resuelve reproducción, progreso, mute y continuidad sin simular contenido estático.' },
          { name: 'Google Cloud Storage', use: 'Guarda originales y derivados de media fuera de la base relacional.' },
          { name: 'Background Workers', use: 'Procesan renders e historias fuera del tiempo de respuesta de la API.' },
          { name: 'FFmpeg + Sharp', use: 'Generan variantes, miniaturas y metadatos para entregar media utilizable.' },
          { name: 'Cloud Run', use: 'Aísla la API y los procesos de media para escalarlos y desplegarlos por separado.' },
        ],
      },
      {
        title: 'De un Toque a una Trama',
        chapter: 'RELACIÓN / REGLAS',
        summary: 'Una señal unilateral sólo se transforma cuando existe reciprocidad.',
        signal: 'El interés necesitaba una acción simple, pero también una regla clara para no presentar una relación que todavía no existía.',
        decision: 'Definí el Toque como interés unilateral. Sólo la reciprocidad entre Cliente y Tienda activa una Trama persistente.',
        result: 'La interfaz comunica intención y relación como estados diferentes, con continuidad y trazabilidad.',
        proof: 'Toques y Tramas aparecen como objetos y recorridos diferenciados; la activación depende de una condición recíproca.',
        tech: [
          { name: 'Modelo de estados', use: 'Representa interés emitido, reciprocidad y relación activa sin atajos semánticos.' },
          { name: 'API REST', use: 'Recibe la acción y aplica la regla antes de devolver el nuevo estado.' },
          { name: 'Prisma', use: 'Ejecuta la lectura y la escritura del vínculo dentro de operaciones tipadas.' },
          { name: 'PostgreSQL', use: 'Persiste Toques y Tramas con la continuidad y trazabilidad del dominio.' },
          { name: 'React', use: 'Traduce el estado del dominio a mensajes y acciones comprensibles.' },
        ],
      },
      {
        title: 'Operación que también deja evidencia',
        chapter: 'ADMINISTRACIÓN / GOBIERNO',
        summary: 'Publicar no alcanza: alguien debe poder revisar, corregir y operar.',
        signal: 'Un sistema con actores, contenidos y reglas necesita control interno, no solamente interfaces públicas atractivas.',
        decision: 'Incorporé superficies de Administración, estados verificables y límites operativos para no esconder el funcionamiento detrás del diseño.',
        result: 'La operación puede inspeccionar actividad y actuar sin convertir cada ajuste en una modificación de código.',
        proof: 'El repositorio contiene dashboard, administración de actividad, planes y herramientas específicas de operación.',
        tech: [
          { name: 'React', use: 'Construye herramientas densas de operación sin separarlas del mismo lenguaje de producto.' },
          { name: 'Firebase Auth', use: 'Valida la identidad antes de habilitar una superficie o una acción administrativa.' },
          { name: 'API REST', use: 'Centraliza decisiones que no deben depender de una interfaz o dispositivo particular.' },
          { name: 'PostgreSQL', use: 'Conserva estados operativos y evidencia revisable por el sistema.' },
          { name: 'Redis', use: 'Aporta caché, coordinación y Pub/Sub a procesos que necesitan compartir señales.' },
          { name: 'Background Workers', use: 'Ejecutan mantenimiento y sincronizaciones sin bloquear la operación principal.' },
        ],
      },
      {
        title: 'Catálogo, mapa y conversación',
        chapter: 'DESCUBRIMIENTO / COMERCIO',
        summary: 'La actividad conduce a una Tienda, un producto o una conversación concreta.',
        signal: 'Descubrir una marca no debía terminar en una card aislada: hacía falta contexto comercial y continuidad.',
        decision: 'Conecté feeds, mapas, catálogo, preguntas de producto y carrito como partes de una misma experiencia de descubrimiento.',
        result: 'Cliente puede pasar de mirar actividad a explorar una Tienda y actuar sobre productos sin perder el contexto.',
        proof: 'La aplicación incluye ModaFeed, mapa público, catálogo, preguntas de producto y un drawer de carrito implementados en el producto real.',
        tech: [
          { name: 'MapLibre + Leaflet', use: 'Renderizan el mapa como superficie de descubrimiento y mantienen un motor alternativo.' },
          { name: 'React', use: 'Mantiene el contexto entre feed, Tienda, producto, pregunta y carrito.' },
          { name: 'API REST', use: 'Entrega catálogo, actividad y respuestas del dominio desde una fuente gobernada.' },
          { name: 'PostgreSQL', use: 'Relaciona Tiendas, productos, actividad y conversación sin duplicar la verdad del sistema.' },
          { name: 'Redis', use: 'Reduce trabajo repetido y protege las superficies públicas con caché y control de frecuencia.' },
        ],
      },
      {
        title: 'Identidad y releases sin cortar sesiones',
        chapter: 'SSO / OPERACIÓN',
        summary: 'Entrar por la superficie correcta y actualizar sin interrumpir una tarea sensible.',
        signal: 'Distrito Moda y AVVIVO comparten identidad, pero resuelven actores y recorridos distintos; además, una actualización podía aparecer durante un formulario o una operación.',
        decision: 'Construí intercambio SSO, resolución posterior del actor, rutas separadas y una actualización diferida cuando existe trabajo sensible en curso.',
        result: 'Cada sesión llega a Cliente, Tienda o Administración según corresponde y los releases respetan la continuidad de uso.',
        proof: 'El producto implementa puente SSO, rutas por actor, manifiesto de versión, coordinación entre pestañas y stream de auditoría.',
        tech: [
          { name: 'Google One Tap', use: 'Inicia el acceso asistido cuando el navegador y la configuración lo permiten.' },
          { name: 'Firebase Auth', use: 'Intercambia y valida identidad antes de resolver el recorrido final.' },
          { name: 'React Router', use: 'Separa superficies de Cliente, Tienda y Administración sin mezclar permisos.' },
          { name: 'Redis Pub/Sub', use: 'Distribuye señales de chat y auditoría entre instancias sin convertirlas en estado local.' },
          { name: 'Vite + manifest', use: 'Publica una versión identificable que permite detectar una actualización disponible.' },
          { name: 'Firebase Hosting', use: 'Entrega el frontend y enruta solicitudes hacia los servicios productivos.' },
          { name: 'Cloud Run', use: 'Despliega API y servicios sin acoplar su ciclo de release al frontend.' },
        ],
      },
    ],
  },
  {
    id: 'aye',
    number: '02',
    title: 'CATÁLOGO AYE',
    subtitle: 'Catálogo automatizado',
    type: 'COMMERCE / AUTOMATION',
    statement: 'Una fuente externa convertida en una experiencia comercial administrable, compartible y preparada para móvil.',
    role: 'Importación · Catálogo · Checkout humano · Administración · SEO · PWA',
    accent: '#ff9828',
    url: 'https://ayenatura-e4388.web.app/',
    host: 'ayenatura-e4388.web.app',
    embeddable: true,
    stack: [
      { name: 'React 19', use: 'Construye storefront, carrito, checkout y administración.' },
      { name: 'TypeScript 7', use: 'Mantiene productos, promociones y pedidos con contratos explícitos.' },
      { name: 'Vite 8', use: 'Compila la SPA, divide código y ejecuta el generador social del build.' },
      { name: 'Tailwind CSS 4', use: 'Resuelve el sistema visual responsive del catálogo.' },
      { name: 'Firebase Auth', use: 'Identifica a la administradora mediante Google.' },
      { name: 'Cloud Firestore', use: 'Sincroniza destacados y promociones sin republicar código.' },
      { name: 'Firebase Hosting', use: 'Sirve la SPA, las rutas de producto y los assets versionados.' },
      { name: 'Node.js Importer', use: 'Descarga y normaliza manualmente cada ciclo del catálogo.' },
      { name: 'Natura JSON Feed', use: 'Actúa como fuente estructurada externa del snapshot importado.' },
      { name: 'Dynamic Import', use: 'Deja los cientos de productos fuera de la primera pintura.' },
      { name: 'localStorage', use: 'Conserva carrito y favoritos sin crear una base de compradores.' },
      { name: 'Web Share API', use: 'Abre el share nativo del dispositivo cuando está disponible.' },
      { name: 'WhatsApp Deep Link', use: 'Entrega pedido o producto mediante `wa.me`; no simula una Business API.' },
      { name: 'PWA', use: 'Permite instalar el catálogo con identidad propia.' },
      { name: 'Service Worker', use: 'Cachea el shell, ofrece fallback y elimina versiones anteriores.' },
      { name: 'Cache API', use: 'Versiona recursos propios del build sin cachear imágenes externas.' },
      { name: 'Open Graph Generator', use: 'Crea metadata estática específica para cada producto.' },
    ],
    tracks: [
      {
        title: 'Del feed al catálogo utilizable',
        chapter: 'DATOS / AUTOMATIZACIÓN',
        summary: 'Una fuente extensa deja de ser un archivo y se vuelve producto.',
        signal: 'Cargar y mantener manualmente cada ciclo de Natura no era una operación sostenible para una revendedora independiente.',
        decision: 'Construí un importador que obtiene el feed y normaliza nombres, precios, disponibilidad, imágenes, categorías y líneas.',
        result: 'Cada ciclo puede regenerar un snapshot tipado y coherente, listo para búsqueda, catálogo y publicación.',
        proof: 'El snapshot auditado del ciclo 2026-13 contiene 937 productos; 851 figuraban disponibles al momento de la importación.',
        tech: [
          { name: 'Node.js', use: 'Ejecuta el pipeline de importación fuera de la interfaz pública.' },
          { name: 'TypeScript', use: 'Mantiene un contrato consistente entre datos importados y componentes del catálogo.' },
          { name: 'JSON generado', use: 'Entrega un snapshot reproducible y versionable sin depender del feed durante cada visita.' },
        ],
      },
      {
        title: 'Encontrar antes que recorrer',
        chapter: 'CATÁLOGO / EXPLORACIÓN',
        summary: 'Cientos de productos no deberían sentirse como cientos de obstáculos.',
        signal: 'En una pantalla móvil, recorrer todo el catálogo hasta encontrar un tono, una línea o un producto era demasiado costoso.',
        decision: 'Combiné búsqueda amplia, categorías, disponibilidad, favoritos y orden por nombre o precio.',
        result: 'La grilla recalcula localmente y entrega primero un conjunto manejable, sin bloquear la exploración.',
        proof: 'La búsqueda real contempla nombre, descripción, código, categoría, línea, volumen y color; el catálogo pagina la exposición inicial.',
        tech: [
          { name: 'React', use: 'Coordina filtros, resultados, favoritos y estados de catálogo sin recargar la página.' },
          { name: 'TypeScript', use: 'Conserva la forma de cada producto en búsqueda, cards, carrito y share.' },
          { name: 'Tailwind CSS', use: 'Resuelve una interfaz densa y responsive manteniendo consistencia visual.' },
        ],
      },
      {
        title: 'Un carrito que termina en conversación',
        chapter: 'PEDIDO / WHATSAPP',
        summary: 'El sistema ordena el pedido; Aye conserva la confirmación final.',
        signal: 'La clienta necesitaba recibir selecciones claras sin simular pagos, stock confirmado ni una compra automática inexistente.',
        decision: 'Persistí carrito y favoritos localmente; antes del envío pido nombre, dirección, localidad e indicaciones.',
        result: 'El sitio compone el detalle y el total estimado, y abre WhatsApp para que Aye confirme precio, disponibilidad, pago y entrega.',
        proof: 'Los datos del checkout se agregan al mensaje y no se guardan en la página; la interfaz lo explica antes de continuar.',
        tech: [
          { name: 'localStorage', use: 'Conserva carrito y favoritos en el dispositivo sin crear una base de compradores.' },
          { name: 'React', use: 'Mantiene cantidades, resumen y validaciones del checkout.' },
          { name: 'WhatsApp', use: 'Entrega un pedido legible a la conversación donde ocurre la confirmación humana.' },
        ],
      },
      {
        title: 'Promociones controladas por la clienta',
        chapter: 'ADMIN / CAMPAÑA',
        summary: 'Cambiar la vidriera no requiere volver a publicar el producto.',
        signal: 'Aye necesitaba mover destacados y descuentos por ciclo sin tocar código ni depender de una edición técnica.',
        decision: 'Creé un panel con acceso Google y autorización en Firestore para elegir hasta diez productos y descuentos gobernados.',
        result: 'La portada recibe su configuración en vivo desde un documento remoto, mientras el catálogo base permanece intacto.',
        proof: 'El panel admite títulos predefinidos y descuentos de 5, 10 o 15 por ciento; las reglas reservan su escritura a una administradora activa.',
        tech: [
          { name: 'Firebase Auth', use: 'Identifica a la administradora antes de habilitar la operación.' },
          { name: 'Cloud Firestore', use: 'Publica la configuración de la vidriera y la sincroniza con la home.' },
          { name: 'Security Rules', use: 'Evita que la autorización dependa de ocultar un botón en el frontend.' },
        ],
      },
      {
        title: 'Cada producto tiene su propia puerta',
        chapter: 'SHARE / SEO SOCIAL',
        summary: 'Compartir una card abre ese producto, no una home genérica.',
        signal: 'Un enlace único para todo el catálogo perdía imagen, nombre y contexto del producto elegido.',
        decision: 'El build genera una ruta estática por producto con canonical y Open Graph propios, más Web Share con fallback a WhatsApp.',
        result: 'La vista social recibe datos específicos y la SPA vuelve a abrir el catálogo filtrado en el producto compartido.',
        proof: 'Las rutas `/producto/<id>/` se generan durante cada build a partir del snapshot real.',
        tech: [
          { name: 'Vite', use: 'Produce el build y deja el punto de extensión para generar las páginas sociales.' },
          { name: 'Open Graph', use: 'Entrega imagen, nombre y descripción específicos a cada preview.' },
          { name: 'Web Share API', use: 'Usa el diálogo nativo cuando existe y recurre a WhatsApp cuando no.' },
        ],
      },
      {
        title: 'Catálogo grande, arranque liviano',
        chapter: 'PERFORMANCE / PWA',
        summary: 'La cantidad de producto no debía sentirse en la primera pintura.',
        signal: 'Incluir el catálogo completo en la carga inicial demoraba la interfaz más importante: la que permite empezar.',
        decision: 'Separé metadata inicial, importación dinámica del catálogo, suscripción diferida, imágenes lazy y un service worker versionado.',
        result: 'La interfaz aparece primero, el catálogo entra después y la aplicación puede instalar su shell para visitas recurrentes.',
        proof: 'El bundle carga el snapshot en un chunk posterior y el service worker elimina cachés anteriores al cambiar de versión.',
        tech: [
          { name: 'Dynamic import', use: 'Deja el bloque de productos fuera de la ruta crítica de render.' },
          { name: 'Service Worker', use: 'Cachea el shell propio y conserva un fallback básico sin apropiarse de imágenes externas.' },
          { name: 'PWA', use: 'Permite instalar el catálogo con identidad propia en dispositivos compatibles.' },
        ],
      },
    ],
  },
  {
    id: 'rise',
    number: '03',
    title: 'RISE DIFUSIÓN',
    subtitle: 'Plataforma cultural',
    type: 'MUSIC / CULTURE',
    statement: 'Servicios musicales, obra administrable e identidad pública dentro de una presencia digital independiente.',
    role: 'Producto · Identidad · Copy · Experiencia · Administración · SEO',
    accent: '#8d5cff',
    url: 'https://risedifusion.com.ar/',
    host: 'risedifusion.com.ar',
    embeddable: true,
    stack: [
      { name: 'React 19', use: 'Construye la landing pública y el panel privado.' },
      { name: 'TypeScript 7', use: 'Tipa servicios, formularios y cards administrables.' },
      { name: 'Vite 8', use: 'Compila y optimiza la aplicación de una sola página.' },
      { name: 'Firebase Auth', use: 'Protege el panel mediante acceso con Google.' },
      { name: 'Cloud Firestore', use: 'Publica y ordena cards visibles en tiempo real.' },
      { name: 'WriteBatch', use: 'Guarda el conjunto administrado de manera atómica.' },
      { name: 'Firebase Hosting', use: 'Sirve HTTPS, dominio, rutas y caché de assets.' },
      { name: 'Canvas API', use: 'Reduce imágenes antes de guardarlas.' },
      { name: 'WebP Data URL', use: 'Permite media administrable sin usar Firebase Storage.' },
      { name: 'WhatsApp Deep Link', use: 'Prepara consultas por servicio mediante `wa.me`; no es una Business API.' },
      { name: 'JSON-LD + Open Graph', use: 'Alinea servicios, identidad y previews sociales.' },
      { name: 'Font Awesome', use: 'Aporta iconografía vectorial accesible.' },
    ],
    tracks: [
      {
        title: 'Una puerta para todos los servicios',
        chapter: 'NECESIDAD / ARQUITECTURA',
        summary: 'Cinco propuestas distintas tenían que sonar como una sola marca.',
        signal: 'Distribución, difusión, letras, webs y presencia digital estaban fragmentadas y eran difíciles de comparar.',
        decision: 'Ordené la landing por servicios, plataformas, proceso, preguntas frecuentes y consultas contextualizadas.',
        result: 'Cada persona puede entender, elegir y conversar con Rise sin pasar por una navegación confusa.',
        proof: 'Cada CTA abre WhatsApp con el servicio elegido y el formulario compone una consulta completa.',
        tech: [
          { name: 'React', use: 'Mantiene servicios, preguntas y formularios dentro de una experiencia continua.' },
          { name: 'CSS propio', use: 'Construye la identidad musical sin depender de una plantilla visual.' },
          { name: 'WhatsApp', use: 'Conserva el contexto del servicio al iniciar la conversación.' },
        ],
      },
      {
        title: 'Distribución sin promesas falsas',
        chapter: 'COPY / CONFIANZA',
        summary: 'Vender un servicio también implica explicar correctamente sus límites.',
        signal: 'La distribución necesitaba ser clara sin presentar a Rise como dueño del proceso que revisa una plataforma externa.',
        decision: 'Separé acompañamiento de Rise, revisión de RouteNote y condiciones propias de las plataformas.',
        result: 'La propuesta comercial comunica alcance, identidad y descubrimiento sin deformar el funcionamiento real.',
        proof: 'La página enlaza la plataforma externa y presenta disclaimers visibles dentro del recorrido de distribución.',
        tech: [
          { name: 'Contenido estructurado', use: 'Distribuye beneficios, proceso y límites en el momento donde cada uno hace falta.' },
          { name: 'RouteNote link', use: 'Conecta con la plataforma real sin atribuirse una infraestructura ajena.' },
          { name: 'React', use: 'Mantiene el contexto de la consulta cuando la persona decide avanzar.' },
        ],
      },
      {
        title: 'Obra administrable sin tocar código',
        chapter: 'ADMIN / FIRESTORE',
        summary: 'La landing dejó de ser una pieza cerrada después del lanzamiento.',
        signal: 'Rise necesitaba actualizar artistas y proyectos sin depender de una nueva compilación por cada cambio.',
        decision: 'Construí `/admin` con acceso Google, edición, orden, visibilidad y publicación atómica.',
        result: 'La portada se suscribe a cards ordenadas y muestra solamente las visibles, con respaldo local si el remoto no responde.',
        proof: 'El panel publica toda la colección en una escritura batch y el frontend conserva cinco casos de respaldo.',
        tech: [
          { name: 'Firebase Auth', use: 'Protege el acceso a la herramienta de gestión.' },
          { name: 'Cloud Firestore', use: 'Sincroniza obra visible y orden sin volver a publicar la landing.' },
          { name: 'React', use: 'Resuelve edición, previsualización y estados de guardado.' },
        ],
      },
      {
        title: 'Imágenes sin servidor ni Storage',
        chapter: 'MEDIA / ARQUITECTURA',
        summary: 'Una restricción de infraestructura se transformó en una regla de producto.',
        signal: 'Las cards necesitaban fotos administrables, pero el proyecto no debía sumar servidor propio ni Firebase Storage.',
        decision: 'Reduzco a 1200 px, convierto a WebP en el navegador y valido peso antes de guardar la Data URL en Firestore.',
        result: 'Rise administra imágenes dentro de una arquitectura gratuita, con topes explícitos en interfaz y reglas.',
        proof: 'El sistema limita la colección a 15 cards y valida el tamaño de la imagen tanto en cliente como en Firestore.',
        tech: [
          { name: 'Canvas API', use: 'Redimensiona la imagen antes de enviarla a la base.' },
          { name: 'WebP', use: 'Reduce el peso conservando una calidad útil para cards públicas.' },
          { name: 'Firestore Rules', use: 'Repite los límites críticos fuera de la interfaz de administración.' },
        ],
      },
      {
        title: 'Identidad pública verificable',
        chapter: 'SEO / PUBLICACIÓN',
        summary: 'La misma marca debe ser reconocible en pantalla, buscadores y shares.',
        signal: 'Una dirección visual fuerte perdía valor si dominio, metadata y contenido público decían cosas diferentes.',
        decision: 'Alineé canonical, Open Graph, Twitter, datos estructurados, sitemap, robots y contenido visible.',
        result: 'Rise se presenta con una identidad consistente ante personas, plataformas sociales y buscadores.',
        proof: 'El sitio declara Organization, ProfessionalService, catálogo de servicios, FAQ y WebSite; `/admin` permanece fuera de indexación.',
        tech: [
          { name: 'JSON-LD', use: 'Describe marca, servicios y preguntas con estructuras legibles por buscadores.' },
          { name: 'Open Graph', use: 'Conserva identidad e imagen cuando el dominio se comparte.' },
          { name: 'Firebase Hosting', use: 'Publica dominio, headers y rutas del producto.' },
        ],
      },
    ],
  },
  {
    id: 'hembra',
    number: '04',
    title: 'HEMBRA',
    subtitle: 'Comercio botánico',
    type: 'BRAND / COMMERCE',
    statement: 'Una marca artesanal convertida en tienda, operación administrable y sistema de universos visuales.',
    role: 'Marca · Catálogo · Comercio · Administración · Media · QA',
    accent: '#db7d93',
    url: 'https://hembra-accesorios.web.app/',
    host: 'hembra-accesorios.web.app',
    embeddable: true,
    stack: [
      { name: 'React 19', use: 'Construye tienda, catálogo, bolsa y panel de administración.' },
      { name: 'TypeScript 5.8', use: 'Tipa productos, variantes, universos y operación.' },
      { name: 'Vite 6', use: 'Compila el storefront y sus herramientas internas.' },
      { name: 'Tailwind CSS 4', use: 'Resuelve el sistema visual responsive.' },
      { name: 'Firebase Auth', use: 'Restringe administración a las cuentas configuradas.' },
      { name: 'Cloud Firestore', use: 'Guarda productos, universos y media administrable.' },
      { name: 'Firestore REST v1', use: 'Permite al Worker leer exclusivamente productos publicados para construir previews.' },
      { name: 'Firebase Hosting', use: 'Sirve la aplicación pública principal.' },
      { name: 'React Context', use: 'Comparte bolsa y favoritos entre las superficies comerciales.' },
      { name: 'localStorage', use: 'Conserva bolsa, favoritos y fallbacks en el dispositivo.' },
      { name: 'WhatsApp Deep Link', use: 'Entrega consultas y pedidos por `wa.me`; no es una Business API.' },
      { name: 'Canvas + WebP', use: 'Comprime fotografías en el navegador antes de persistirlas.' },
      { name: 'Cloudflare Worker', use: 'Genera respuestas sociales específicas por producto en el borde.' },
      { name: 'Cloudflare Pages', use: 'Publica la superficie de previews compartibles.' },
      { name: 'Open Graph', use: 'Entrega imagen y contexto del producto a cada enlace social.' },
      { name: 'Playwright', use: 'Ejecuta smokes de producción en escritorio y móvil.' },
      { name: 'Font Awesome + Lucide', use: 'Aportan iconografía para marca, comercio y administración.' },
    ],
    tracks: [
      {
        title: 'Tienda con identidad',
        chapter: 'NECESIDAD / MARCA',
        summary: 'Vender sin borrar el carácter artesanal de HEMBRA.',
        signal: 'La marca necesitaba una experiencia comercial completa sin quedar reducida a una grilla genérica de productos.',
        decision: 'Construí una landing responsive con hero, categorías, productos, relato de marca, universos, preguntas y contacto.',
        result: 'HEMBRA conserva un lenguaje editorial propio mientras conduce con claridad hacia la exploración y la consulta.',
        proof: 'La obra pública reúne marca, catálogo, relato y contacto dentro de un mismo recorrido responsive.',
        tech: [
          { name: 'React', use: 'Compone la narrativa de marca y las superficies comerciales como un único producto.' },
          { name: 'Tailwind CSS', use: 'Mantiene ritmo y jerarquía desde móvil hasta escritorio.' },
          { name: 'CSS propio', use: 'Aporta el tono botánico y editorial que diferencia a la marca.' },
        ],
      },
      {
        title: 'Catálogo que ayuda a elegir',
        chapter: 'EXPLORACIÓN / PRODUCTO',
        summary: 'Encontrar una pieza por intención, no por paciencia.',
        signal: 'Las personas debían poder reducir el catálogo según lo que buscaban y no recorrerlo completo cada vez.',
        decision: 'Organicé búsqueda, categoría, stock, ofertas y precio; sólo los productos publicados llegan a la vista pública.',
        result: 'La exploración responde a disponibilidad e intención sin mezclar borradores con oferta real.',
        proof: 'Los filtros y la condición de publicación están implementados en la vista de catálogo productiva.',
        tech: [
          { name: 'React', use: 'Recalcula catálogo, filtros y estados de interacción en la misma vista.' },
          { name: 'Cloud Firestore', use: 'Provee el conjunto administrado de productos y su estado público.' },
          { name: 'TypeScript', use: 'Conserva variantes, stock y datos de producto entre catálogo, bolsa y administración.' },
        ],
      },
      {
        title: 'Venta humana, sin checkout ficticio',
        chapter: 'BOLSA / WHATSAPP',
        summary: 'La web prepara la decisión; la marca confirma la venta.',
        signal: 'HEMBRA necesitaba pedidos completos sin fingir un cobro o una confirmación automática que no existían.',
        decision: 'La bolsa conserva cantidades, variantes y colores, calcula un total estimado y prepara el mensaje final.',
        result: 'Favoritos, consultas individuales y pedido convergen en WhatsApp con el contexto necesario para continuar.',
        proof: 'La confirmación y el pago quedan expresamente fuera del sitio; el estado comercial se prepara sin prometer lo que no controla.',
        tech: [
          { name: 'React Context', use: 'Comparte bolsa y favoritos entre catálogo, ficha y acciones de compra.' },
          { name: 'localStorage', use: 'Conserva selecciones en el dispositivo entre visitas.' },
          { name: 'WhatsApp', use: 'Recibe el detalle preparado en el canal donde la marca confirma.' },
        ],
      },
      {
        title: 'Administración gobernada',
        chapter: 'ADMIN / REGLAS',
        summary: 'Gestionar catálogo sin convertir el panel en una puerta abierta.',
        signal: 'La operación requería altas, edición, publicación y stock con límites que protegieran la calidad del catálogo.',
        decision: 'Creé acceso Google con cuentas autorizadas y un alta en tres pasos que exige imagen y valida topes.',
        result: 'La marca puede operar productos sin tocar código y las reglas críticas no dependen sólo del formulario.',
        proof: 'El sistema limita 15 productos por categoría y 6 fotos por producto; publicación y stock forman parte del flujo.',
        tech: [
          { name: 'Firebase Auth', use: 'Identifica las cuentas autorizadas para administrar.' },
          { name: 'Cloud Firestore', use: 'Guarda catálogo y estados de operación.' },
          { name: 'Security Rules', use: 'Refuerza permisos y estructura en la capa de datos.' },
        ],
      },
      {
        title: 'Una plataforma, varios universos',
        chapter: 'EDITOR / CONTENIDO',
        summary: 'La marca puede crecer sin quedar encerrada en un solo catálogo.',
        signal: 'HEMBRA necesitaba presentar líneas creativas con identidad propia y actualizarlas después del lanzamiento.',
        decision: 'Cada universo administra identidad, portada, color, enlace, slider y piezas desde un editor con vista escritorio y móvil.',
        result: 'El contenido editorial evoluciona de manera independiente sin romper la estructura común de la tienda.',
        proof: 'Los medios viven en subcolecciones separadas y el editor ofrece previsualización responsive antes de guardar.',
        tech: [
          { name: 'React', use: 'Sincroniza editor, orden de piezas y preview en dos formatos.' },
          { name: 'Firestore', use: 'Separa cada universo y sus medios en colecciones administrables.' },
          { name: 'Responsive preview', use: 'Permite validar una composición antes de exponerla en móvil o escritorio.' },
        ],
      },
      {
        title: 'Imágenes y enlaces listos para compartir',
        chapter: 'MEDIA / EDGE',
        summary: 'Cada producto público puede viajar con su propia identidad.',
        signal: 'Las fotos administrables necesitaban peso controlado y los shares debían mostrar el producto correcto.',
        decision: 'Comprimo a WebP en navegador y genero URLs estables; un Worker lee sólo productos publicados y arma su metadata social.',
        result: 'Las imágenes permanecen manejables y cada enlace puede entregar un preview específico antes de abrir la tienda.',
        proof: 'El flujo cuenta con una ruta pública de previews y una prueba de producción que verifica la salida compartible.',
        tech: [
          { name: 'Canvas + WebP', use: 'Reduce las imágenes antes de persistirlas.' },
          { name: 'Cloudflare Worker', use: 'Construye metadata social en el borde usando sólo datos publicados.' },
          { name: 'Playwright', use: 'Comprueba el comportamiento crítico del sitio y las rutas de producción.' },
        ],
      },
    ],
  },
  {
    id: 'anto',
    number: '05',
    title: 'ANTO GRISPO',
    subtitle: 'Fotografía profesional',
    type: 'PHOTOGRAPHY / IDENTITY',
    statement: 'Una obra recuperada y convertida en portfolio narrativo, accesible y autoadministrable.',
    role: 'Recuperación · Narrativa · Identidad · Portfolio · Administración · Publicación',
    accent: '#5dd6b5',
    url: 'https://ph-antogrispo.web.app/',
    host: 'ph-antogrispo.web.app',
    embeddable: true,
    stack: [
      { name: 'React 19', use: 'Construye portfolio, galerías, lightbox y panel.' },
      { name: 'TypeScript 7', use: 'Tipa secciones, piezas y contenido administrable.' },
      { name: 'Vite 8', use: 'Compila y publica la experiencia recuperada.' },
      { name: 'Firebase Auth', use: 'Protege el panel con una lista cerrada de cuentas.' },
      { name: 'Cloud Firestore', use: 'Sincroniza el portfolio mediante `onSnapshot`.' },
      { name: 'WriteBatch', use: 'Publica la edición completa sin dejar un estado parcial.' },
      { name: 'Firebase Hosting', use: 'Sirve el portfolio y fue fuente de la recuperación original.' },
      { name: 'Canvas + WebP', use: 'Reduce y convierte imágenes antes de guardarlas.' },
      { name: 'CSS Grid + Scroll Snap', use: 'Construye bento, retratos y colecciones con ritmos distintos.' },
      { name: 'Keyboard Navigation', use: 'Abre y recorre el lightbox con Enter, espacio, Escape y flechas.' },
      { name: 'Reduced Motion', use: 'Respeta la preferencia de movimiento del sistema.' },
      { name: 'WhatsApp Deep Link', use: 'Compone la consulta y abre `wa.me` sin fingir un backend.' },
      { name: 'JSON-LD + Open Graph', use: 'Presenta identidad profesional y previews sociales.' },
      { name: 'Font Awesome', use: 'Aporta iconografía vectorial accesible.' },
    ],
    tracks: [
      {
        title: 'Recuperar antes de rediseñar',
        chapter: 'NECESIDAD / RESCATE',
        summary: 'La fuente se había perdido, pero la obra publicada seguía hablando.',
        signal: 'El repositorio original estaba vacío y no existía una base editable confiable para continuar el portfolio.',
        decision: 'Reconstruí la fuente desde Firebase Hosting, preservando textos, estructura visual y 30 recursos locales.',
        result: 'La obra volvió a tener código, contexto y continuidad sin inventar un historial que no existía.',
        proof: 'El contexto canónico documenta la recuperación y el nuevo repositorio conserva los recursos reconstruidos.',
        tech: [
          { name: 'Firebase Hosting', use: 'Fue la evidencia pública utilizada para recuperar la obra existente.' },
          { name: 'React', use: 'Convirtió la recuperación en una base editable y mantenible.' },
          { name: 'Vite', use: 'Provee un build moderno para continuar el producto recuperado.' },
        ],
      },
      {
        title: 'Un portfolio que narra',
        chapter: 'DIRECCIÓN / EXPERIENCIA',
        summary: 'La fotografía se recorre como una historia, no como un inventario.',
        signal: 'Shows, retratos y colecciones necesitaban ritmos distintos para que la obra no quedara aplastada en una única grilla.',
        decision: 'Diseñé hero de siete imágenes, bento para escenas, retratos editoriales y colecciones horizontales con scroll snap.',
        result: 'Cada cuerpo de trabajo conserva su escala y el recorrido alterna impacto, detalle y pausa.',
        proof: 'La experiencia pública combina reproducción automática y elección manual en hero con tres sistemas de galería diferentes.',
        tech: [
          { name: 'React', use: 'Coordina selección, reproducción y composición de las distintas colecciones.' },
          { name: 'CSS Grid', use: 'Construye el bento de escenas sin sacrificar comportamiento responsive.' },
          { name: 'Scroll Snap', use: 'Da cadencia táctil a las colecciones horizontales.' },
        ],
      },
      {
        title: 'Exploración fotográfica accesible',
        chapter: 'INTERACCIÓN / ACCESO',
        summary: 'La ampliación también funciona con teclado y movimiento reducido.',
        signal: 'Una galería visual no podía depender exclusivamente del mouse ni imponer animación a todas las personas.',
        decision: 'Implementé lightbox descriptivo, anterior/siguiente, navegación móvil, Escape, flechas y activación por teclado.',
        result: 'La obra se explora con mouse, toque o teclado y respeta la preferencia de movimiento reducido.',
        proof: 'Las cards responden a Enter y espacio; el lightbox acepta Escape y flechas; las revelaciones contemplan `prefers-reduced-motion`.',
        tech: [
          { name: 'React', use: 'Gestiona foco, índice activo y navegación entre fotografías.' },
          { name: 'Keyboard API', use: 'Conecta Escape y flechas con el lightbox sin acciones ocultas.' },
          { name: 'Reduced Motion', use: 'Reduce las transiciones cuando el sistema operativo lo solicita.' },
        ],
      },
      {
        title: 'Portfolio autoadministrable',
        chapter: 'ADMIN / CONTENIDO',
        summary: 'La fotógrafa puede editar obra sin romper las reglas de cada sección.',
        signal: 'Hero, selección, retratos y colecciones no admitían exactamente la misma cantidad ni el mismo tipo de contenido.',
        decision: 'Incorporé `/admin` con Google, cuentas cerradas, validación por sección y publicación batch en `portfolioItems`.',
        result: 'La obra cambia desde un panel propio, manteniendo mínimos, máximos y orden antes de publicar.',
        proof: 'El guardado valida el conjunto completo y escribe sus cambios de manera atómica.',
        tech: [
          { name: 'Firebase Auth', use: 'Restringe el panel a las cuentas autorizadas.' },
          { name: 'Cloud Firestore', use: 'Publica el contenido editable que consume el portfolio.' },
          { name: 'Write Batch', use: 'Evita dejar una edición a mitad de camino cuando cambia el conjunto.' },
        ],
      },
      {
        title: 'Imágenes administrables sin Storage',
        chapter: 'MEDIA / REGLAS',
        summary: 'La fotografía se optimiza antes de entrar al sistema.',
        signal: 'Permitir archivos originales sin control podía volver lenta e inestable la experiencia pública.',
        decision: 'El navegador limita el lado mayor, convierte a WebP y reduce calidad antes de guardar la Data URL.',
        result: 'La administración mantiene imágenes utilizables sin sumar Firebase Storage al producto.',
        proof: 'Las reglas validan estructura y tamaño, y reservan la escritura para cuentas autorizadas.',
        tech: [
          { name: 'Canvas API', use: 'Redimensiona y recomprime cada archivo antes de persistirlo.' },
          { name: 'WebP', use: 'Reduce transferencia conservando una calidad apropiada para portfolio.' },
          { name: 'Firestore Rules', use: 'Valida tamaño, forma y permiso fuera de la interfaz.' },
        ],
      },
      {
        title: 'El portfolio termina en conversación',
        chapter: 'CONTACTO / SEO',
        summary: 'La consulta sale estructurada y la identidad viaja con el enlace.',
        signal: 'Una llamada a la acción genérica no aportaba el contexto necesario para cotizar una producción.',
        decision: 'El formulario reúne nombre, correo, fecha, tipo y detalle; luego abre WhatsApp con la consulta preparada.',
        result: 'La fotógrafa recibe un punto de partida concreto, mientras canonical, shares y datos estructurados presentan su identidad profesional.',
        proof: 'El formulario funciona sin fingir un backend y la publicación incluye canonical, Open Graph, Twitter y JSON-LD.',
        tech: [
          { name: 'React', use: 'Valida y compone los datos de la consulta antes de salir.' },
          { name: 'WhatsApp', use: 'Abre la conversación con la producción ya contextualizada.' },
          { name: 'JSON-LD', use: 'Describe públicamente la identidad profesional para buscadores.' },
        ],
      },
    ],
  },
]

// Each track points to the implementation behind the case, not inferred business metrics.
const metalStack: ProjectTech[] = [
  { name: 'HTML5', use: 'Entrega el catálogo público como contenido estático y navegable.' },
  { name: 'JavaScript', use: 'Coordina el visor, las galerías, el zoom y las acciones para compartir.' },
  { name: 'React', use: 'Compone el ventanal interactivo y la administración privada.' },
  { name: 'TypeScript', use: 'Define contratos del catálogo, la experiencia y los borradores.' },
  { name: 'SVG + Canvas', use: 'Construye vidrio, hierro y luz con gráficos vectoriales e interacción.' },
  { name: 'Vite', use: 'Compila las entradas públicas y administrativas por separado.' },
  { name: 'Node.js + Sharp', use: 'Optimiza imágenes y genera páginas y portadas sociales por pieza.' },
  { name: 'Firebase Auth', use: 'Identifica al editor mediante Google en el panel privado.' },
  { name: 'Cloud Firestore', use: 'Protege los borradores con reglas y revisión transaccional.' },
  { name: 'Firebase Hosting', use: 'Publica el catálogo y sus rutas estáticas.' },
  { name: 'Playwright', use: 'Comprueba recorridos y permisos con pruebas aisladas.' },
]
const cieloStack: ProjectTech[] = [
  { name: 'React', use: 'Compone el archivo editorial y el reproductor interactivo.' },
  { name: 'TypeScript', use: 'Modela álbumes, piezas, momentos y personas con contratos explícitos.' },
  { name: 'React Router', use: 'Asigna una URL a cada entidad del archivo.' },
  { name: 'Vite', use: 'Compila la experiencia y prepara la generación estática.' },
  { name: 'SVG', use: 'Conserva los signos reconstruidos y las capas visuales del archivo.' },
  { name: 'Spotify', use: 'Integra el reproductor oficial mediante su iFrame API y controles por gesto.' },
  { name: 'Firebase Auth', use: 'Identifica a los editores autorizados mediante Google.' },
  { name: 'Cloud Firestore', use: 'Guarda fichas y borradores con control de conflictos.' },
  { name: 'Node.js + Sharp', use: 'Genera HTML por ruta y tarjetas sociales optimizadas.' },
  { name: 'Firebase Hosting', use: 'Sirve el archivo público con rutas y páginas de error reales.' },
  { name: 'Web Share', use: 'Comparte la URL de cada obra desde dispositivos compatibles.' },
]
const metalRepo = 'https://github.com/Tellounder/metalmentearte'
const cieloRepo = 'https://github.com/Tellounder/cielofinal'

projects.push(
  {
    id: 'metalmente', number: '06', title: 'MetalMente Arte', subtitle: 'Obra, proceso y materia',
    type: 'CATÁLOGO EDITORIAL / EXPERIENCIA INTERACTIVA',
    statement: 'El archivo de un taller, convertido en un catálogo interactivo de herrería artística y restauraciones.',
    role: 'Producto · UX/UI · Frontend · Contenido · Administración · SEO técnico',
    accent: '#d5b176', url: 'https://metalmentearte.web.app/', host: 'metalmentearte.web.app',
    repository: metalRepo, embeddable: true, stack: metalStack,
    tracks: [
      {
        title: 'Del archivo al catálogo', chapter: 'CONTENIDO / PRODUCTO',
        summary: 'Piezas y procesos que se pueden descubrir, comparar y consultar.',
        signal: 'Las fotos sueltas no explicaban la obra ni el proceso del taller.',
        decision: 'Organicé trabajos por categoría, con fichas, IDs y rutas estables.',
        result: '12 trabajos y 25 fotografías forman un catálogo navegable.',
        proof: 'Catálogo tipado con cuatro categorías y fichas por trabajo.',
        evidenceUrl: `${metalRepo}#el-problema`, tech: [metalStack[0], metalStack[1], metalStack[3]],
      },
      {
        title: 'Una identidad que responde', chapter: 'IDENTIDAD / INTERACCIÓN',
        summary: 'Hierro, vidrio y luz forman parte del recorrido.',
        signal: 'La identidad del taller necesitaba sentirse en la interfaz.',
        decision: 'Diseñé un ventanal con SVG y Canvas, sensible al puntero y al scroll.',
        result: 'Una experiencia propia que respeta la preferencia de movimiento reducido.',
        proof: 'Ventanal interactivo construido como componente independiente.',
        evidenceUrl: `${metalRepo}/blob/main/src/WindowExperience.tsx`, tech: [metalStack[2], metalStack[3], metalStack[4]],
      },
      {
        title: 'El detalle sin recortes', chapter: 'VISOR / ACCESIBILIDAD',
        summary: 'Acercarse a la materia desde escritorio o celular.',
        signal: 'Las texturas y etapas de restauración necesitaban una mirada cercana.',
        decision: 'Implementé lupa, zoom, navegación táctil y controles de teclado.',
        result: 'Cada pieza puede inspeccionarse conservando la proporción de la fotografía.',
        proof: 'Visor con presentación adaptable a escritorio y móvil.',
        evidenceUrl: `${metalRepo}/blob/main/src/project-viewer.js`, tech: [metalStack[1], metalStack[0]],
      },
      {
        title: 'Cada obra tiene su enlace', chapter: 'DISTRIBUCIÓN / SEO',
        summary: 'Compartir una pieza concreta con su imagen y contexto.',
        signal: 'Un enlace genérico perdía la pieza que motivaba la consulta.',
        decision: 'Generé páginas y tarjetas por trabajo y foto, con canonical y datos estructurados.',
        result: '38 páginas y portadas sociales listas para compartir.',
        proof: 'Generador de HTML y Open Graph a partir del catálogo.',
        evidenceUrl: `${metalRepo}/blob/main/scripts/generate-seo.mjs`, tech: [metalStack[5], metalStack[6], metalStack[9]],
      },
      {
        title: 'Borrador no es producción', chapter: 'ADMINISTRACIÓN / PERMISOS',
        summary: 'Editar con control sobre lo que termina publicado.',
        signal: 'El catálogo debía actualizarse sin publicar cambios por accidente.',
        decision: 'Separé el panel privado, los borradores y la publicación; agregué control de conflictos.',
        result: 'El editor prepara contenido protegido antes de incorporarlo al sitio público.',
        proof: 'Google Auth, reglas por propietario y revisión transaccional de borradores.',
        evidenceUrl: `${metalRepo}/blob/main/docs/administracion.md`, tech: [metalStack[7], metalStack[8], metalStack[2]],
      },
      {
        title: 'Publicar con evidencia', chapter: 'CALIDAD / PUBLICACIÓN',
        summary: 'Comprobar rutas, contenido y permisos antes de publicar.',
        signal: 'Los cambios podían romper enlaces o filtrar referencias privadas.',
        decision: 'Sumé validadores de catálogo y SEO, y pruebas aisladas de administración.',
        result: 'El build rechaza borradores y recursos privados en el catálogo público.',
        proof: 'Validación de snapshot público y pruebas con emulador.',
        evidenceUrl: `${metalRepo}/blob/main/scripts/validate-public-snapshot.mjs`, tech: [metalStack[3], metalStack[10], metalStack[5]],
      },
    ],
  },
  {
    id: 'cielofinal', number: '07', title: 'Cielofinal', subtitle: 'Un archivo con memoria',
    type: 'ARCHIVO CULTURAL / EXPERIENCIA MUSICAL',
    statement: 'La música y la historia de una banda, reunidas en un archivo digital navegable y compartible.',
    role: 'Dirección visual · UX · Frontend · Contenido · Spotify · Administración · SEO',
    accent: '#8eafe0', url: 'https://cielofinal.web.app/', host: 'cielofinal.web.app',
    repository: cieloRepo, embeddable: true, stack: cieloStack,
    tracks: [
      {
        title: 'De material disperso a archivo', chapter: 'MEMORIA / CONTENIDO',
        summary: 'Música, portadas y fuentes dentro de una misma lectura.',
        signal: 'El legado estaba repartido entre imágenes, canciones y recuerdos.',
        decision: 'Modelé álbumes, piezas, momentos y personas con relaciones y URLs propias.',
        result: '6 ediciones y 61 entradas de repertorio recorren 18 páginas públicas.',
        proof: 'Contenido estructurado y generación de páginas por entidad.',
        evidenceUrl: `${cieloRepo}#readme`, tech: [cieloStack[0], cieloStack[1], cieloStack[2]],
      },
      {
        title: 'Un disco que se toca y escucha', chapter: 'MÚSICA / INTERACCIÓN',
        summary: 'Explorar el archivo desde un vinilo interactivo.',
        signal: 'El recorrido musical necesitaba algo más que una lista de enlaces.',
        decision: 'Conecté un vinilo arrastrable y controles accesibles al reproductor oficial de Spotify.',
        result: 'El visitante inicia, pausa y recorre la música mediante acciones explícitas.',
        proof: 'Interacción con inercia y teclado conectada a Spotify iFrame API.',
        evidenceUrl: `${cieloRepo}/blob/main/src/experience/SpotifyVinyl.tsx`, tech: [cieloStack[0], cieloStack[5], cieloStack[4]],
      },
      {
        title: 'Historia con fuentes y matices', chapter: 'EDICIÓN / TRAZABILIDAD',
        summary: 'Preservar la memoria sin convertir dudas en hechos.',
        signal: 'Fechas y atribuciones no siempre coincidían entre las fuentes.',
        decision: 'Separé grabación, edición y publicación digital, conservando matices y pendientes.',
        result: 'El archivo explica su contexto sin presentar una formación histórica como actual.',
        proof: 'Fuentes y criterios editoriales documentados junto al contenido.',
        evidenceUrl: `${cieloRepo}/tree/main/docs`, tech: [cieloStack[1], cieloStack[2]],
      },
      {
        title: 'Editar sin romper lo publicado', chapter: 'ADMINISTRACIÓN / CONTINUIDAD',
        summary: 'Fichas administrables y límites de edición explícitos.',
        signal: 'Actualizar información básica no debía requerir editar código cada vez.',
        decision: 'Incorporé Google Auth, borradores y control transaccional para las fichas administrables.',
        result: 'La edición distingue contenido guardado, publicado y pendiente de recompilar.',
        proof: 'Administración parcial con protección ante conflictos y sin borrado definitivo.',
        evidenceUrl: `${cieloRepo}/blob/main/docs/administracion.md`, tech: [cieloStack[6], cieloStack[7], cieloStack[0]],
      },
      {
        title: 'Cada obra tiene su dirección', chapter: 'DISTRIBUCIÓN / SEO',
        summary: 'Una URL y una portada para compartir cada disco.',
        signal: 'Compartir el inicio del sitio perdía el álbum que se quería mostrar.',
        decision: 'Generé HTML por ruta, metadata, Open Graph y acciones de compartir.',
        result: '18 páginas estáticas y 7 tarjetas sociales presentan el archivo y sus discos.',
        proof: 'Prerender, sitemap y portadas de 1200 × 630 declarados en el proyecto.',
        evidenceUrl: `${cieloRepo}/blob/main/docs/seo.md`, tech: [cieloStack[8], cieloStack[10], cieloStack[9]],
      },
      {
        title: 'Reconstruir identidad sin inventarla', chapter: 'IDENTIDAD / PRESERVACIÓN',
        summary: 'El diseño parte del material histórico recibido.',
        signal: 'Las portadas y signos necesitaban continuidad en una nueva superficie digital.',
        decision: 'Reconstruí recursos vectoriales y conservé su procedencia junto a los originales.',
        result: 'Una identidad editorial propia del archivo, con movimiento reducido disponible.',
        proof: 'Manifiesto de recursos, monograma reconstruido y portadas versionadas.',
        evidenceUrl: `${cieloRepo}/blob/main/public/assets/manifest.json`, tech: [cieloStack[4], cieloStack[0], cieloStack[8]],
      },
    ],
  },
)
